#!/bin/bash
#
# chkconfig: 3 85 15
# description: send-notify system.

case "$1" in
  start)
        /usr/local/iganari/notify-server/bin/send-notify.sh wakeup
        ;;
  stop)
        /usr/local/iganari/notify-server/bin/send-notify.sh sleep
        ;;
  *)
        echo $"Usage: send-notify {start|stop}"
esac
